name: Run OCR Script

on:
  workflow_dispatch:   # 手動執行
  schedule:
    - cron: "0 0 * * *"   # 每天 00:00 UTC 執行一次

jobs:
  ocr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Tesseract
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-chi-tra

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
        pip install requests pillow pytesseract gspread google-auth google-api-python-client

      - name: Setup credentials
        run: echo '${{ secrets.GCP_KEY }}' > service_account.json

      - name: Run script
        run: python script.py
